version: '2'

services:
  client:
    image: 'mitra-client:latest'
    build:
      context: .
    container_name: client
    ports:
      - 8701:8701
    environment:
      - APP_MAINAPPURL=http://main:8700

